### ISSUE TITLE
merge --method here into inside-build and rename inside-build to local-build

### ISSUE THREAD

**Issue by TomasTomecek** [DBuildService/dock#59] opened 2015-03-24 07:29 UTC
* [ ] merge `--method here` into `inside-build` -- these are very similar
 * [ ] we might need to create/update input plugin for this
* [ ] rename `inside-build` to `local-build` -- not very important, but `local-build` might be more clear

**Comment by jpopelka** [comment] 2015-05-07 13:11
Duplicate of #85

**Closed by jpopelka** 2015-05-07 13:11 UTC
Labels: enhancement

**Comment by TomasTomecek** [comment] 2015-05-11 07:12
good catch
